## Introduction to NumPy Arrays

In this script, we will learn the basics of NumPy arrays, including how to create arrays, generate arrays using different functions, understand array attributes and methods, and reshape arrays. This is foundational knowledge for working with NumPy effectively.

**Basic Array Creation**

We can create a NumPy array from a Python list using the `np.array()` function.

In [1]:
import numpy as np

Create a 1D array from a list

In [2]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


You can also create arrays from lists containing different data types. NumPy will upcast to a common type if needed.

List with mixed types

In [3]:
a = [1, 2, 3.5]
print("Original list:", a)

Original list: [1, 2, 3.5]


Convert to NumPy array (note the data type upcasting to float)

In [4]:
arr_mixed = np.array(a)
print("NumPy array:", arr_mixed)

NumPy array: [1.  2.  3.5]


Creating Multi-dimensional Arrays

You can create 2D or higher dimensional arrays by passing nested lists.

2D list

In [5]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr_2d = np.array(l)
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Array Generation Functions**

NumPy provides several functions to generate arrays with specific patterns or values.

Generate values from 1 to 10 with step 2

In [6]:
arr = np.arange(1, 11, 2)
print(arr)

[1 3 5 7 9]


Create an array of zeros with shape (4, 8)

In [7]:
zeros_arr = np.zeros((4, 8))
print(zeros_arr)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


Create an array of ones with shape (6, 6)

In [8]:
ones_arr = np.ones((6, 6))
print(ones_arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


Create 100 evenly spaced values between 0 and 1

In [9]:
linspace_arr = np.linspace(0, 1, 100)
print(linspace_arr)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

**Random Number Generation**

NumPy can generate random numbers from different distributions.

Generate 10 random numbers from uniform distribution [0,1)

In [10]:
rand_vals = np.random.rand(10)
print(rand_vals)

[0.27274933 0.98967144 0.17775813 0.78998861 0.5945733  0.56938588
 0.78461293 0.18207735 0.53780531 0.66689764]


Generate 10 random numbers from standard normal distribution

In [11]:
randn_vals = np.random.randn(10)
print(randn_vals)

[ 1.69625513 -2.81686016 -1.71967708 -1.32684124  0.68186127  0.57849428
  0.49384002  0.84339379 -1.0490028   3.09962407]


Generate 10 random integers between 10 and 20

In [12]:
randint_vals = np.random.randint(10, 20, 10)
print(randint_vals)

[17 12 13 11 11 18 18 10 16 11]


**Array Attributes**

Arrays have attributes that describe their shape, size, and data type.

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array:")
print(arr)
print("\nShape:", arr.shape)  # Dimensions of the array
print("\nSize:", arr.size)    # Total number of elements
print("\nData type:", arr.dtype)  # Data type of elements

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape: (3, 3)

Size: 9

Data type: int64


**Array Methods**

NumPy arrays have many useful methods for computations.

In [14]:
print("Minimum value:", arr.min())
print("Maximum value:", arr.max())
print("Sum of all elements:", arr.sum())
print("Sum along axis 1 (rows):", np.sum(arr, axis=1))
print("Mean value:", arr.mean())
print("Standard deviation:", arr.std())
print("Index of max value:", arr.argmax())
print("Index of min value:", arr.argmin())

Minimum value: 1
Maximum value: 9
Sum of all elements: 45
Sum along axis 1 (rows): [ 6 15 24]
Mean value: 5.0
Standard deviation: 2.581988897471611
Index of max value: 8
Index of min value: 0


**Reshaping and Resizing Arrays**

You can change the shape of an array without changing its data using `reshape`.

In [15]:
arr = np.arange(1, 31)
print("Original array:", arr)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


Reshape to 6 rows and 5 columns

In [16]:
reshaped_arr = arr.reshape(6, 5)
print("Reshaped array (6x5):")
print(reshaped_arr)

Reshaped array (6x5):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


Exercise:
Try creating arrays using different NumPy functions like `arange`, `zeros`, `ones`, and `linspace`. Experiment with reshaping arrays and observe their attributes.