## NumPy Array Operations

This script covers arithmetic operations on arrays, broadcasting, deep vs shallow copies, matrix operations, and advanced array manipulations like stacking and splitting.

In [1]:
import numpy as np

#### ARRAY OPERATION

**Arithmetic Operations**

In [2]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])

In [3]:
print("Array a1:", a1)
print("Array a2:", a2)

Array a1: [1 2 3 4 5]
Array a2: [ 6  7  8  9 10]


In [4]:
print("Addition:", a1 + a2)
print("Subtraction:", a1 - a2)
print("Multiplication:", a1 * a2)
print("Division:", a1 / a2)
print("Floor Division:", a1 // a2)
print("Exponentiation:", a1 ** a2)

Addition: [ 7  9 11 13 15]
Subtraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Floor Division: [0 0 0 0 0]
Exponentiation: [      1     128    6561  262144 9765625]


Multiply array by scalar

In [5]:
print("Array a1 multiplied by 2:", a1 * 2)

Array a1 multiplied by 2: [ 2  4  6  8 10]


**Broadcasting**

In [6]:
l = [10, 20, 30, 40]
arr = np.array(l)
print("Original array:", arr)

Original array: [10 20 30 40]


Add scalar to array (broadcasting)

In [7]:
print("Array after adding 10:", arr + 10)

Array after adding 10: [20 30 40 50]


Create a 5x5 array

In [8]:
arr2 = np.arange(1, 26).reshape(5, 5)
print("Original 5x5 array:\n", arr2)

Original 5x5 array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Add scalar to array

In [9]:
arr2 = arr2 + 10
print("Array after adding 10:\n", arr2)

Array after adding 10:
 [[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


**Deep and Shallow Copy**

In [10]:
a = np.arange(1, 21)
print("Original array a:", a)

Original array a: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Create a slice (shallow copy)

In [11]:
slice_a = a[:5]
print("Slice of a:", slice_a)

Slice of a: [1 2 3 4 5]


Modify the slice

In [12]:
slice_a = slice_a * 10
print("Modified slice:", slice_a)

Modified slice: [10 20 30 40 50]


Original array remains unchanged because slice_a is a new array after multiplication

In [13]:
print("Original array a after modifying slice:", a)

Original array a after modifying slice: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Modify a slice of original array directly

In [14]:
a[4:6] = a[4:6] * 10
print("Original array a after modifying elements 4 and 5:", a)

Original array a after modifying elements 4 and 5: [ 1  2  3  4 50 60  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Create a deep copy

In [15]:
b = a.copy()
b[0] = 99
print("Deep copy b after modification:", b)
print("Original array a remains unchanged:", a)

Deep copy b after modification: [99  2  3  4 50 60  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Original array a remains unchanged: [ 1  2  3  4 50 60  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


**Matrix Operations**

In [16]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [17]:
print("Matrix A:\n", A)
print("Matrix B:\n", B)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]


Matrix multiplication

In [18]:
print("Dot product of A and B:\n", np.dot(A, B))

Dot product of A and B:
 [[19 22]
 [43 50]]


Transpose of A

In [19]:
print("Transpose of A:\n", A.T)

Transpose of A:
 [[1 3]
 [2 4]]


**Advanced Array Manipulation**

Stacking arrays vertically and horizontally

In [20]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [21]:
print("Array a:", a)
print("Array b:", b)

Array a: [1 2 3 4]
Array b: [5 6 7 8]


In [22]:
print("Vertical stack:\n", np.vstack((a, b)))
print("Horizontal stack:\n", np.hstack((a, b)))
print("Column stack:\n", np.column_stack((a, b)))

Vertical stack:
 [[1 2 3 4]
 [5 6 7 8]]
Horizontal stack:
 [1 2 3 4 5 6 7 8]
Column stack:
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


**Splitting arrays**

In [23]:
c = np.arange(16).reshape(4, 4)
print("Original array c:\n", c)

Original array c:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Horizontal split into 4 parts

In [24]:
hsplit = np.hsplit(c, 4)
print("Horizontal split into 4 parts:")
for part in hsplit:
    print(part)

Horizontal split into 4 parts:
[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1]
 [ 5]
 [ 9]
 [13]]
[[ 2]
 [ 6]
 [10]
 [14]]
[[ 3]
 [ 7]
 [11]
 [15]]


Vertical split into 2 parts

In [25]:
vsplit = np.vsplit(c, 2)
print("Vertical split into 2 parts:")
for part in vsplit:
    print(part)

Vertical split into 2 parts:
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


Exercise:
 Practice arithmetic operations, broadcasting, and array manipulations. Try stacking and splitting arrays of different shapes.