## NumPy Indexing and Slicing

In this script, we will learn how to index and slice NumPy arrays, including vectors and matrices. We will also cover boolean indexing, which is a powerful way to filter arrays based on conditions.

In [1]:
import numpy as np

**Indexing and Slicing of Vectors**

Create an array from 11 to 20

In [2]:
arr = np.arange(11, 21)
print("Original array:", arr)

Original array: [11 12 13 14 15 16 17 18 19 20]


Slice the array starting from index 3 to the end, taking every 2nd element

In [3]:
arr_slice = arr[3::2]
print("Sliced array (from index 3, step 2):", arr_slice)

Sliced array (from index 3, step 2): [14 16 18 20]


Access a single element by index

In [4]:
print("Element at index 4:", arr[4])

Element at index 4: 15


**Indexing and Slicing of Matrices**

Create a 6x5 matrix with values from 1 to 30

In [5]:
arr = np.arange(1, 31).reshape(6, 5)
print("Original 6x5 matrix:\n", arr)

Original 6x5 matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


Slice the matrix from row 3 to end and column 3 to end

In [6]:
slice_matrix = arr[3:, 3:]
print("Sliced matrix (rows 3 to end, columns 3 to end):\n", slice_matrix)

Sliced matrix (rows 3 to end, columns 3 to end):
 [[19 20]
 [24 25]
 [29 30]]


Access all rows in column 2

In [7]:
print("All rows, column 2:", arr[:, 2])

All rows, column 2: [ 3  8 13 18 23 28]


**Boolean Indexing**

Create an array from 11 to 20

In [8]:
arr = np.arange(11, 21)
print("Original array:", arr)

Original array: [11 12 13 14 15 16 17 18 19 20]


Create a boolean index for even numbers

In [9]:
bool_index = arr % 2 == 0
print("Boolean index for even numbers:", bool_index)

Boolean index for even numbers: [False  True False  True False  True False  True False  True]


Use boolean indexing to filter array elements

In [10]:
filtered_arr = arr[bool_index]
print("Filtered array (even numbers):", filtered_arr)

Filtered array (even numbers): [12 14 16 18 20]


Exercise:
 Try creating your own arrays and practice slicing with different start, stop, and step values. Experiment with boolean indexing using different conditions.