## NumPy Exercises

This script contains practical exercises to apply NumPy concepts, including Sudoku validation and general data manipulation tasks.

In [1]:
import numpy as np

**Exercise 1: Valid Sudoku Check**

Define a Sudoku grid as a 9x9 NumPy array

In [2]:
sudoku = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

Check if each row sums to 45 (sum of numbers 1 to 9)

In [3]:
row_sums = np.sum(sudoku, axis=1)
for i, total in enumerate(row_sums):
    if total != 45:
        print(f"Sudoku is not valid in row {i}")
        break
else:
    print("Sudoku rows are valid")

Sudoku rows are valid


Check sums of each 3x3 subgrid

In [4]:
print("Sum of each 3x3 subgrid:")
for i in range(0, 9, 3):
    for j in range(0, 9, 3):
        subgrid = sudoku[i:i+3, j:j+3]
        print(subgrid.sum())

Sum of each 3x3 subgrid:
45
45
45
45
45
45
45
45
45


**Exercise 2: General Data Manipulation Questions**

In [5]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [6]:
#Get the shape of the matrix.

data_shape = data.shape
print("Data shape:", data_shape)

Data shape: (5, 3)


In [7]:
#Find the average age of students.

average_age = np.mean(data[:, 0])
print("Average age:", average_age)

Average age: 18.4


In [8]:
#Extract Math marks of all students.

math_marks = data[:, 1]
print("Math marks:", math_marks)

Math marks: [85 92 76 65 90]


In [9]:
#Find the highest Science mark.

highest_science_mark = np.max(data[:, 2])
print("Highest Science mark:", highest_science_mark)

Highest Science mark: 95


In [10]:
#Get details of the student who scored more than 90 in Math.

students_above_90_math = data[data[:, 1] > 90]
print("Students scoring above 90 in Math:\n", students_above_90_math)

Students scoring above 90 in Math:
 [[19 92 88]]


In [11]:
#Increase Math marks of all students by 5.

data[:, 1] += 5
print("Math marks after adding 5:\n", data[:, 1])

Math marks after adding 5:
 [90 97 81 70 95]


In [12]:
#Find how many students are younger than 19.

younger_students_count = np.sum(data[:, 0] < 19)
print("Number of students younger than 19:", younger_students_count)

Number of students younger than 19: 3


In [13]:
#Calculate the average marks in each subject (column-wise mean).

average_marks = np.mean(data[:, 1:], axis=0)
print("Average marks in Math and Science:", average_marks)

Average marks in Math and Science: [86.6 83.2]


In [14]:
#Get data of students who scored at least 80 in both subjects.

students_above_80_both = data[(data[:, 1] >= 80) & (data[:, 2] >= 80)]
print("Students scoring at least 80 in both subjects:\n", students_above_80_both)

Students scoring at least 80 in both subjects:
 [[19 97 88]
 [17 81 95]
 [20 95 85]]


In [15]:
#Replace all Science marks < 75 with 0.

data[:, 2][data[:, 2] < 75] = 0
print("Science marks after replacing values less than 75 with 0:\n", data[:, 2])

Science marks after replacing values less than 75 with 0:
 [78 88 95  0 85]


Exercise:
 Try modifying the data array to add more students or subjects. Practice filtering and aggregating data using NumPy.